#!/usr/bin/env bash


#### Variables ==start ####

export PATH="/bin:/usr/bin"
UNIT="node-bmw"
APP_DIR="/usr/local/${UNIT}"
OLD_PWD="${PWD}"

#### Variables ==final ####


#### Functions ==start ####

log() {
	sudo logger -s -t "${UNIT}" "${1}" 2>&1
}

sleep_msg() {
	log "Sleeping."
	sleep 0.5
}

follow() {
	sudo journalctl -o cat -u ${UNIT} -f -n 0
}

status() {
	echo -e "Checking status of ${UNIT}.\n"
	sudo systemctl status ${UNIT}
}

restart() {
	stop
	sleep_msg
	start
	sleep_msg
	status
}

stop() {
	log "Stopping ${UNIT}."
	sudo systemctl stop ${UNIT}
	sleep_msg
	status
}

start() {
	log "Starting ${UNIT}."
	sudo systemctl start ${UNIT}
	sleep_msg
	status
}

update() {
	cd ${APP_DIR}

	GIT_BRANCH="$(git branch | grep '*' | sed 's/^*\ //g')"
	sudo git fetch origin ${GIT_BRANCH} &> /dev/null

	GIT_LOG="$(git log HEAD..origin/${GIT_BRANCH} --oneline)"
	[[ -z "${GIT_LOG}" ]] && log "No ${UNIT} update needed" && return

	log "${UNIT} update available!"

	log "Downloading ${UNIT} update"
	sudo git pull

	log "Performing npm global update"
	sudo npm -g update

	log "Performing local npm install"
	sudo npm install

	log "Performing local npm update"
	sudo npm update

	log "Performing --unsafe-perm install of serialport"
	sudo npm install --unsafe-perm --build-from-source serialport

	restart

	cd "${OLD_PWD}"
}

#### Functions ==final ####

${1-status}
