#!/usr/bin/env bash

UNIT="node-bmw"
APP_DIR="/usr/local/${UNIT}"
OLD_PWD="${PWD}"

sleep_msg() {
	echo "Sleeping."
	sleep 1
}

status() {
	echo -e "Checking status of ${UNIT}.\n"
	systemctl status ${UNIT}
}

restart() {
	stop
	sleep_msg
	start
	sleep_msg
	status
}

stop() {
	echo "Stopping ${UNIT}."
	systemctl stop ${UNIT}
	sleep_msg
	status
}

start() {
	echo "Starting ${UNIT}."
	systemctl start ${UNIT}
	sleep_msg
	status
}

update() {
	cd ${APP_DIR}

	GIT_BRANCH="$(git branch | sed 's/^*\ //g')"
	git fetch origin ${GIT_BRANCH} > /dev/null 2>&1

	GIT_LOG="$(git log HEAD..origin/${GIT_BRANCH} --oneline)"

	if [[ -z "${GIT_LOG}" ]]; then
		echo "No ${UNIT} update needed"
	else
		echo "${UNIT} update available!"

		echo "Downloading ${UNIT} update"
		git fetch
		git pull

		restart
	fi

	cd "${OLD_PWD}"
}

[[ ${1} ]] && ${1} || status
