#!/usr/bin/env bash

BASE="http://localhost:3001/lcm?"
SLEEP="0.01"

#HFL="output_highbeam_front_left=true"
#HFR="output_highbeam_front_right=true"
HFL=""
HFR=""
SFL="output_standing_front_left=true"
SFR="output_standing_front_right=true"
TFR="output_turn_front_right=true"
TFL="output_turn_front_left=true"
TRL="output_turn_rear_left=true"
TRR="output_turn_rear_right=true"
SORL="output_standing_rear_left=true"
SORR="output_standing_rear_right=true"
BRL="output_brake_rear_left=true"
BRR="output_brake_rear_right=true"
RRL="output_reverse_rear_left=true"
RRR="output_reverse_rear_right=true"

while true; do
	curl "${BASE}" -d "${HFR}&${RRR}&${SORL}&${BRR}&${SFR}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d "${HFR}&${TRL}&${SORL}&${BRR}&${SFR}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d "${HFR}&${RRR}&${SORR}&${BRL}&${SFL}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORR}&${BRL}&${SFL}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${RRR}&${SORL}&${BRR}&${SFR}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORL}&${BRR}&${SFR}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${RRR}&${SORR}&${BRL}&${SFL}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORR}&${BRL}&${SFL}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${SORL}&${BRR}&${SFR}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d "${TRR}&${SORL}&${BRR}&${SFR}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${SORR}&${BRL}&${SFL}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORR}&${BRL}&${SFL}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${RRL}&${SORL}&${BRR}&${SFR}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORL}&${BRR}&${SFR}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${RRL}&${SORR}&${BRL}&${SFL}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORR}&${BRL}&${SFL}&${TFL}" ; sleep ${SLEEP}

	curl "${BASE}" -d "${HFL}&${RRR}&${SORL}&${BRR}&${SFR}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d "${HFL}&${TRL}&${SORL}&${BRR}&${SFR}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d "${HFL}&${RRR}&${SORR}&${BRL}&${SFL}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORR}&${BRL}&${SFL}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${RRR}&${SORL}&${BRR}&${SFR}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORL}&${BRR}&${SFR}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${SORR}&${BRL}&${SFL}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORR}&${BRL}&${SFL}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${RRL}&${SORL}&${BRR}&${SFR}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d "${TRR}&${SORL}&${BRR}&${SFR}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${SORR}&${BRL}&${SFL}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORR}&${BRL}&${SFL}&${TFR}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${RRL}&${SORL}&${BRR}&${SFR}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORL}&${BRR}&${SFR}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d        "${RRL}&${SORR}&${BRL}&${SFL}&${TFL}" ; sleep ${SLEEP}
	curl "${BASE}" -d               "${SORR}&${BRL}&${SFL}&${TFL}" ; sleep ${SLEEP}
done
