#!/usr/bin/env node

var status = {
	audio : {
		audio_control : 'off',
		dsp_ready     : false,
		rad_ready     : false,
	},
	bt_device : {
		connected : false,
		name      : 'bt-device',
		path      : '/org/bluez/hci0/dev_XX_XX_XX_XX_XX_XX',
		service   : 'org.bluez.Device1',
	},
	coding : {
		since_service : {
			days   : null,
			liters : null,
		},
		unit : {
			cons     : null,
			distance : null,
			speed    : null,
			temp     : null,
			time     : null,
		}
	},
	engine : {
		speed   : null,
		running : null,
	},
	flaps : {
		hood        : null,
		trunk       : null,
		front_left  : null,
		front_right : null,
		rear_left   : null,
		rear_right  : null,
	},
	hdmi : {
		client_ready  : null,
		physical_addr : null,
		power_status  : null,
	},
	ihka : {
		ac_status : null,
	},
	ike : {
		alarm_siren_on        : null,
		aux_heat_on           : null,
		aux_vent_on           : null,
		gear_p                : null,
		gear_r                : null,
		handbrake_on          : null,
		immobiliser_on        : null,
		motor_running         : null,
		oil_pressure_low      : null,
		reverse_not_plausible : null,
		temp_f                : null,
		vehicle_driving       : null,
	},
	immobilizer : {
		immobilized : null,
		key_number  : null,
		key_present : null,
	},
	kodi : {
		player_id   : null,
		player_type : null,
	},
	lcm : {
		io : {
			bitmask_0  : null,
			bitmask_1  : null,
			bitmask_2  : null,
			bitmask_2  : null,
			bitmask_3  : null,
			bitmask_4  : null,
			bitmask_5  : null,
			bitmask_6  : null,
			bitmask_7  : null,
			bitmask_8  : null,
			bitmask_9  : null,
			bitmask_10 : null,
			bitmask_11 : null,
			bitmask_12 : null,
			bitmask_13 : null,
			bitmask_14 : null,
			bitmask_15 : null,
			bitmask_16 : null,
			bitmask_17 : null,
			bitmask_18 : null,
			bitmask_19 : null,
			bitmask_20 : null,
			bitmask_21 : null,
			bitmask_22 : null,
			bitmask_23 : null,
			bitmask_24 : null,
			bitmask_25 : null,
			bitmask_26 : null,
			bitmask_27 : null,
			bitmask_28 : null,
			bitmask_29 : null,
			bitmask_30 : null,
			bitmask_31 : null,
		},
		clamp_15                         : null,
		clamp_30a                        : null,
		clamp_30b                        : null,
		clamp_r                          : null,
		dimmer_value_1                   : null,
		dimmer_value_2                   : null,
		input_air_suspension             : null,
		input_armoured_door              : null,
		input_brake_fluid_level          : null,
		input_carb                       : null,
		input_engine_failsafe            : null,
		input_fire_extinguisher          : null,
		input_hold_up_alarm              : null,
		input_key_in_ignition            : null,
		input_kfn                        : null,
		input_preheating_fuel_injection  : null,
		input_seat_belts_lock            : null,
		input_tire_defect                : null,
		input_vertical_aim               : null,
		input_washer_fluid_level         : null,
		mode_failsafe                    : null,
		mode_sleep                       : null,
		output_brake_rear_left           : null,
		output_brake_rear_middle         : null,
		output_brake_rear_right          : null,
		output_fog_front_left            : null,
		output_fog_front_right           : null,
		output_fog_rear_left             : null,
		output_highbeam_front_left       : null,
		output_highbeam_front_right      : null,
		output_led_switch_hazard         : null,
		output_led_switch_light          : null,
		output_license_rear_left         : null,
		output_license_rear_right        : null,
		output_lowbeam_front_left        : null,
		output_lowbeam_front_right       : null,
		output_reverse_rear_left         : null,
		output_reverse_rear_right        : null,
		output_reverse_rear_trailer      : null,
		output_standing_front_left       : null,
		output_standing_front_right      : null,
		output_standing_inner_rear_left  : null,
		output_standing_inner_rear_right : null,
		output_standing_rear_left        : null,
		output_standing_rear_right       : null,
		output_turn_front_left           : null,
		output_turn_front_right          : null,
		output_turn_rear_left            : null,
		output_turn_rear_right           : null,
		switch_brake                     : null,
		switch_fog_front                 : null,
		switch_fog_rear                  : null,
		switch_hazard                    : null,
		switch_highbeam                  : null,
		switch_highbeam_flash            : null,
		switch_lowbeam_1                 : null,
		switch_lowbeam_2                 : null,
		switch_standing                  : null,
		switch_turn_left                 : null,
		switch_turn_right                : null,
	},
	lights : {
		auto : {
			active         : false,
			dimmer_value_1 : null,
			dimmer_value_2 : null,
			dimmer_value_3 : null,
			interval       : null,
			lowbeam        : null,
			reason         : null,
			standing       : null,
		},
		all_off                 : null,
		brake                   : null,
		dimmer_value_3          : null,
		fog_front               : null,
		fog_rear                : null,
		hazard                  : null,
		highbeam                : null,
		interior                : null,
		lowbeam                 : null,
		reverse                 : null,
		standing_front          : null,
		standing_rear           : null,
		trailer                 : null,
		trailer_reverse         : null,
		turn_comfort_left       : null,
		turn_comfort_right      : null,
		turn_fast               : null,
		turn_left               : null,
		turn_left_depress_time  : 0,
		turn_left_release_time  : 0,
		turn_right              : null,
		turn_right_depress_time : 0,
		turn_right_release_time : 0,
		turn_sync               : null,
		welcome_lights          : true,
		welcome_lights_interval : null,
		welcome_lights_level    : 0,
		faulty : {
			all_ok              : null,
			brake_left          : null,
			brake_right         : null,
			fog_front           : null,
			fog_rear            : null,
			hazard              : null,
			highbeam            : null,
			license_plate       : null,
			lowbeam_left        : null,
			lowbeam_right       : null,
			reverse             : null,
			standing_front      : null,
			standing_rear_left  : null,
			standing_rear_right : null,
			trailer             : null,
			turn_fast           : null,
			turn_left           : null,
			turn_right          : null,
		},
	},
	obc : {
		arrival            : null,
		aux_heat_led       : null,
		aux_heat_timer_1   : null,
		aux_heat_timer_2   : null,
		code               : null,
		consumption_1_l100 : null,
		consumption_1_mpg  : null,
		consumption_2_l100 : null,
		consumption_2_mpg  : null,
		date               : null,
		distance_km        : null,
		distance_mi        : null,
		range_km           : null,
		range_mi           : null,
		speedavg_kmh       : null,
		speedavg_mph       : null,
		speedlimit_kmh     : null,
		speedlimit_mph     : null,
		stopwatch          : null,
		time               : null,
		timer              : null,
	},
	rls : {
		headlight_wipe_interval : null,
	},
	temperature : {
		coolant : {
			c : null,
			f : null,
		},
		exterior : {
			c : null,
			f : null,
			obc : {
				c : null,
				f : null,
			},
		},
	},
	vehicle : {
		handbrake      : null,
		ignition       : 'off',
		ignition_level : null,
		locked         : null,
		reverse        : null,
		vin            : null,
		odometer : {
			km : null,
			mi : null,
		},
		speed : {
			kmh : null,
			mph : null,
		},
	},
	windows : {
		roof        : null,
		front_left  : null,
		front_right : null,
		rear_left   : null,
		rear_right  : null,
	},
}

module.exports = status;
