#!/usr/bin/env node

module.exports = {
  bmbt : {
    ready : false,
    reset : true,
  },
  bt_device : {
    connected : false,
    name      : 'bt-device',
    path      : '/org/bluez/hci0/dev_XX_XX_XX_XX_XX_XX',
    service   : 'org.bluez.Device1',
  },
  cdc : {
    ready : false,
    reset : true,
  },
  coding : {
    since_service : {
      days   : null,
      liters : null,
    },
    unit : {
      cons     : null,
      distance : null,
      speed    : null,
      temp     : null,
      time     : null,
    },
  },
  dbus : {
    last_event : 0,
  },
  dsp : {
    mode      : null,
    ready     : false,
    reset     : true,
    reverb    : null,
    room_size : null,
    eq : {
      band0 : null,
      band1 : null,
      band2 : null,
      band3 : null,
      band4 : null,
      band5 : null,
      band6 : null,
    },
  },
  dspc : {
    ready : false,
    reset : true,
  },
  engine : {
    speed   : null,
    running : null,
  },
  flaps : {
    hood        : null,
    trunk       : null,
    front_left  : null,
    front_right : null,
    rear_left   : null,
    rear_right  : null,
  },
  gm : {
    wiper_status : null,
  },
  hdmi : {
    client_ready  : null,
    physical_addr : null,
    power_status  : null,
  },
  ibus : {
    last_event : 0,
  },
  ihka : {
    ac_status : null,
  },
  ike : {
    alarm_siren_on        : null,
    aux_heat_on           : null,
    aux_vent_on           : null,
    gear_p                : null,
    gear_r                : null,
    handbrake_on          : null,
    immobiliser_on        : null,
    motor_running         : null,
    oil_pressure_low      : null,
    ready                 : false,
    reset                 : true,
    reverse_not_plausible : null,
    temp_f                : null,
    vehicle_driving       : null,
  },
  immobilizer : {
    immobilized : null,
    key_number  : null,
    key_present : null,
  },
  kodi : {
    player_id   : null,
    player_type : null,
  },
  lcm : {
    ready : false,
    reset : true,
    io : {
      bitmask_0  : null,
      bitmask_1  : null,
      bitmask_2  : null,
      bitmask_2  : null,
      bitmask_3  : null,
      bitmask_4  : null,
      bitmask_5  : null,
      bitmask_6  : null,
      bitmask_7  : null,
      bitmask_8  : null,
      bitmask_9  : null,
      bitmask_10 : null,
      bitmask_11 : null,
      bitmask_12 : null,
      bitmask_13 : null,
      bitmask_14 : null,
      bitmask_15 : null,
      bitmask_16 : null,
      bitmask_17 : null,
      bitmask_18 : null,
      bitmask_19 : null,
      bitmask_20 : null,
      bitmask_21 : null,
      bitmask_22 : null,
      bitmask_23 : null,
      bitmask_24 : null,
      bitmask_25 : null,
      bitmask_26 : null,
      bitmask_27 : null,
      bitmask_28 : null,
      bitmask_29 : null,
      bitmask_30 : null,
      bitmask_31 : null,
    },
    clamp : {
      c_15  : null,
      c_30a : null,
      c_30b : null,
      c_r   : null,
    },
    dimmer : {
      value_1 : null,
      value_2 : null,
    },
    input : {
      air_suspension             : null,
      armoured_door              : null,
      brake_fluid_level          : null,
      carb                       : null,
      engine_failsafe            : null,
      fire_extinguisher          : null,
      hold_up_alarm              : null,
      key_in_ignition            : null,
      kfn                        : null,
      preheating_fuel_injection  : null,
      seat_belts_lock            : null,
      tire_defect                : null,
      vertical_aim               : null,
      washer_fluid_level         : null,
    },
    mode : {
      failsafe : null,
      sleep    : null,
    },
    output : {
      brake : {
        rear_left   : null,
        rear_middle : null,
        rear_right  : null,
      },
      fog : {
        front_left  : null,
        front_right : null,
        rear_left   : null,
      },
      highbeam : {
        front_left  : null,
        front_right : null,
      },
      led : {
        switch_hazard : null,
        switch_light  : null,
      },
      license : {
        rear_left  : null,
        rear_right : null,
      },
      lowbeam : {
        front_left  : null,
        front_right : null,
      },
      reverse : {
        rear_left    : null,
        rear_right   : null,
        rear_trailer : null,
      },
      standing : {
        front_left       : null,
        front_right      : null,
        inner_rear_left  : null,
        inner_rear_right : null,
        rear_left        : null,
        rear_right       : null,
      },
      turn : {
        front_left  : null,
        front_right : null,
        rear_left   : null,
        rear_right  : null,
      },
    },
    switch : {
      brake          : null,
      fog_front      : null,
      fog_rear       : null,
      hazard         : null,
      highbeam       : null,
      highbeam_flash : null,
      lowbeam_1      : null,
      lowbeam_2      : null,
      standing       : null,
      turn_left      : null,
      turn_right     : null,
    },
  },
  lights : {
    auto : {
      active         : false,
      dimmer_value_1 : null,
      dimmer_value_2 : null,
      dimmer_value_3 : null,
      lowbeam        : null,
      reason         : null,
      standing       : null,
    },
    all_off                 : null,
    brake                   : null,
    dimmer_value_3          : null,
    fog_front               : null,
    fog_rear                : null,
    hazard                  : null,
    highbeam                : null,
    interior                : null,
    lowbeam                 : null,
    reverse                 : null,
    standing_front          : null,
    standing_rear           : null,
    trailer                 : null,
    trailer_reverse         : null,
    turn_comfort_left       : false,
    turn_comfort_right      : false,
    turn_fast               : null,
    turn_left               : null,
    turn_left_depress_time  : 0,
    turn_left_release_time  : 0,
    turn_right              : null,
    turn_right_depress_time : 0,
    turn_right_release_time : 0,
    turn_sync               : null,
    welcome_lights          : true,
    welcome_lights_interval : null,
    welcome_lights_level    : 0,
    faulty : {
      all_ok        : null,
      hazard        : null,
      highbeam      : null,
      license_plate : null,
      reverse       : null,
      trailer       : null,
      brake : {
        left  : null,
        right : null,
      },
      fog : {
        front : null,
        rear  : null,
      },
      lowbeam : {
        left  : null,
        right : null,
      },
      standing : {
        front      : null,
        rear_left  : null,
        rear_right : null,
      },
      turn : {
        fast  : null,
        left  : null,
        right : null,
      },
    },
  },
  mid : {
    ready : false,
    reset : true,
  },
  obc : {
    arrival      : null,
    aux_heat_led : null,
    code         : null,
    date         : null,
    distance     : null,
    speedlimit   : null,
    stopwatch    : null,
    time         : null,
    timer        : null,
    aux_heat_timer : {
      t1 : null,
      t2 : null,
    },
    consumption : {
      c1 : {
        l100 : null,
        mpg  : null,
      },
      c2 : {
        l100 : null,
        mpg  : null,
      },
    },
    range : {
      km : null,
      mi : null,
    },
    speedavg : {
      kmh : null,
      mph : null,
    },
  },
  rad : {
    audio_control : 'off',
    ready         : false,
    reset         : true,
  },
  rls : {
    headlight_wipe_interval : null,
    wiper_status            : null,
  },
  temperature : {
    coolant : {
      c : null,
      f : null,
    },
    exterior : {
      c : null,
      f : null,
      obc : {
        c : null,
        f : null,
      },
    },
  },
  vehicle : {
    handbrake      : null,
    ignition       : 'off',
    ignition_level : 0,
    locked         : null,
    reverse        : null,
    vin            : null,
    odometer : {
      km : null,
      mi : null,
    },
    speed : {
      kmh : null,
      mph : null,
    },
  },
  windows : {
    roof        : null,
    front_left  : null,
    front_right : null,
    rear_left   : null,
    rear_right  : null,
  },
};
