module.exports = {
  bmbt : {
    ready : false,
    reset : true,
  },
  bt_device : {
    connected : false,
    name      : 'bt-device',
    path      : '/org/bluez/hci0/dev_XX_XX_XX_XX_XX_XX',
    service   : 'org.bluez.Device1',
  },
  cdc : {
    ready : false,
    reset : true,
  },
  coding : {
    since_service : {
      days   : null,
      liters : null,
    },
    unit : {
      cons     : null,
      distance : null,
      speed    : null,
      temp     : null,
      time     : null,
    },
  },
  dbus : {
    last_event : 0,
  },
  dsp : {
		m_audio   : null,
    mode      : null,
    ready     : false,
    reset     : true,
    reverb    : null,
    room_size : null,
    eq : {
      band0 : null,
      band1 : null,
      band2 : null,
      band3 : null,
      band4 : null,
      band5 : null,
      band6 : null,
    },
  },
  dspc : {
    ready : false,
    reset : true,
  },
  engine : {
    speed   : null,
    running : false,
  },
  flaps : {
    hood        : null,
    trunk       : null,
    front_left  : null,
    front_right : null,
    rear_left   : null,
    rear_right  : null,
  },
  gm : {
    wiper_status : null,
  },
  hdmi : {
    client_ready  : null,
    physical_addr : null,
    power_status  : null,
  },
  ibus : {
    last_event : 0,
  },
  ihka : {
    ac_status : null,
  },
  ike : {
    alarm_siren_on        : null,
    aux_heat_on           : null,
    aux_vent_on           : null,
    gear_p                : null,
    gear_r                : null,
    handbrake_on          : null,
    immobiliser_on        : null,
    motor_running         : null,
    oil_pressure_low      : null,
    ready                 : false,
    reset                 : true,
    reverse_not_plausible : null,
    temp_f                : null,
    vehicle_driving       : null,
  },
  immobilizer : {
    immobilized : null,
    key_number  : null,
    key_present : null,
  },
  kodi : {
    player_id   : null,
    player_type : null,
  },
  lcm : {
    ready : false,
    reset : true,
    io : [],
    clamp : {
      c_15  : null,
      c_30a : null,
      c_30b : null,
      c_r   : null,
    },
    dimmer : {
      value_1 : null,
      value_2 : null,
    },
    input : {
      air_suspension             : null,
      armoured_door              : null,
      brake_fluid_level          : null,
      carb                       : null,
      engine_failsafe            : null,
      fire_extinguisher          : null,
      hold_up_alarm              : null,
      key_in_ignition            : null,
      kfn                        : null,
      preheating_fuel_injection  : null,
      seat_belts_lock            : null,
      tire_defect                : null,
      vertical_aim               : null,
      washer_fluid_level         : null,
    },
    mode : {
      failsafe : null,
      sleep    : null,
    },
    output : {
      brake : {
        rear_left   : null,
        rear_middle : null,
        rear_right  : null,
      },
      fog : {
        front_left  : null,
        front_right : null,
        rear_left   : null,
      },
      highbeam : {
        front_left  : null,
        front_right : null,
      },
      led : {
        switch_hazard : null,
        switch_light  : null,
      },
      license : {
        rear_left  : null,
        rear_right : null,
      },
      lowbeam : {
        front_left  : null,
        front_right : null,
      },
      reverse : {
        rear_left    : null,
        rear_right   : null,
        rear_trailer : null,
      },
      standing : {
        front_left       : null,
        front_right      : null,
        inner_rear_left  : null,
        inner_rear_right : null,
        rear_left        : null,
        rear_right       : null,
      },
      turn : {
        front_left  : null,
        front_right : null,
        rear_left   : null,
        rear_right  : null,
      },
    },
		voltage : {
			flash_to_pass      : null,
			terminal_30        : null,
			turn_signal_switch : null,
		},
    switch : {
      brake          : null,
      fog_front      : null,
      fog_rear       : null,
      hazard         : null,
      highbeam       : null,
      highbeam_flash : null,
      lowbeam_1      : null,
      lowbeam_2      : null,
      standing       : null,
      turn_left      : null,
      turn_right     : null,
    },
  },
  lights : {
    auto : {
      active  : false,
      lowbeam : null,
      reason  : null,
    },
		turn : {
      left : {
        active  : false,
        comfort : false,
        depress : null,
      },
      right : {
        active  : false,
        comfort : false,
        depress : null,
      },
			comfort_cool    : true,
			depress_elapsed : null,
			fast            : null,
			sync            : null,
		},
		fog : {
			front : null,
			rear  : null,
		},
    standing : {
      front : null,
      rear  : null,
    },
    trailer : {
      fog      : null,
      reverse  : null,
      standing : null,
    },
    all_off         : null,
    brake           : null,
    dimmer_value_3  : null,
    hazard          : null,
    highbeam        : null,
    interior        : null,
    lowbeam         : null,
    reverse         : null,
    welcome_lights  : false,
    faulty : {
      brake : {
        left  : null,
        right : null,
      },
      fog : {
        front : null,
        rear  : null,
      },
      lowbeam : {
        left  : null,
        right : null,
      },
      standing : {
				rear : {
					left  : null,
					right : null,
				},
				front : null,
      },
      turn : {
        left  : null,
        right : null,
      },
      all_ok        : null,
      highbeam      : null,
      license_plate : null,
      lowbeam       : null,
      reverse       : null,
      trailer       : null,
    },
  },
  mid : {
    ready : false,
    reset : true,
  },
  obc : {
    arrival      : null,
    aux_heat_led : null,
    code         : null,
    date         : null,
    distance     : null,
    speedlimit   : null,
    stopwatch    : null,
    time         : null,
    timer        : null,
    aux_heat_timer : {
      t1 : null,
      t2 : null,
    },
    consumption : {
      c1 : {
        l100 : null,
        mpg  : null,
      },
      c2 : {
        l100 : null,
        mpg  : null,
      },
    },
    range : {
      km : null,
      mi : null,
    },
    speedavg : {
      kmh : null,
      mph : null,
    },
  },
  rad : {
    audio_control : 'off',
    ready         : false,
    reset         : true,
  },
  rls : {
    headlight_wipe_interval : null,
    wiper_status            : null,
  },
  temperature : {
    coolant : {
      c : null,
      f : null,
    },
    exterior : {
      c : null,
      f : null,
      obc : {
        c : null,
        f : null,
      },
    },
  },
  vehicle : {
    handbrake      : false,
    ignition       : 'off',
    ignition_level : 0,
    locked         : null,
    reverse        : false,
    vin            : null,
    odometer : {
      km : null,
      mi : null,
    },
    speed : {
      kmh : null,
      mph : null,
    },
  },
  windows : {
    roof        : null,
    front_left  : null,
    front_right : null,
    rear_left   : null,
    rear_right  : null,
  },
};
