#!/usr/bin/env bash

export PROTO_BMW="http"

if [[ "$(hostname -s)" == *"e39"* ]]; then
	export HOST_BMW="localhost"
	export PORT_BMW="3001"
	export URL_BMW="${PROTO_BMW}://${HOST_BMW}:${PORT_BMW}"
	export URL_BMW_API="${URL_BMW}"
else
	export HOST_BMW="kdm-e39"
	export PORT_BMW="80"
	export URL_BMW="${PROTO_BMW}://${HOST_BMW}:${PORT_BMW}"
	export URL_BMW_API="${PROTO_BMW}://${HOST_BMW}/api"
fi

BASE="${URL_BMW_API}/lcm?"
SLEEP="0"

SFL="output_standing_front_left=true"
SFR="output_standing_front_right=true"
TFR="output_turn_front_right=true"
TFL="output_turn_front_left=true"
TRL="output_turn_rear_left=true"
TRR="output_turn_rear_right=true"
SRL="output_standing_rear_left=true"
SRR="output_standing_rear_right=true"
BRL="output_brake_rear_left=true"
BRM="output_brake_rear_middle=true"
BRR="output_brake_rear_right=true"
RRL="output_reverse_rear_left=true"
RRR="output_reverse_rear_right=true"

while true; do
	curl "${BASE}" -d "${SFR}"
	curl "${BASE}" -d "${TFR}"
	curl "${BASE}" -d "${BRR}"
	curl "${BASE}" -d "${SRR}"
	curl "${BASE}" -d "${TRR}"
	curl "${BASE}" -d "${TRL}"
	curl "${BASE}" -d "${SRL}"
	curl "${BASE}" -d "${BRL}"
	curl "${BASE}" -d "${TFL}"
	curl "${BASE}" -d "${SFL}"
done
